# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  # { :hostname => 'web', :ip => '192.168.0.42', :box => 'bento/ubuntu-18.04', :portfrom => '80', :portto => '8082',
  #   :modules => ["puppet-nginx:2.1.1", "puppetlabs-apt:7.7.1"]
  # },
  # { :hostname => 'appserver', :ip => '192.168.0.43', :box => 'bento/ubuntu-18.04'},
  # { :hostname => 'dbserver',  :ip => '192.168.0.44', :box => 'bento/ubuntu-18.04',
  #   :modules => ["puppetlabs-mysql:10.10.0"]
  # }
  # { :hostname => 'tst0',  :ip => '192.168.0.44', :box => 'bento/ubuntu-18.04'},
  # { :hostname => 'tst1',  :ip => '192.168.0.44', :box => 'bento/ubuntu-18.04'},
  # { :hostname => 'tst2',  :ip => '192.168.0.44', :box => 'bento/ubuntu-18.04'},
]

Vagrant.configure("2") do |config|

  config.vm.provision "install_puppet", before:"all", type: "shell", inline: <<-SHELL
    if which puppet >/dev/null; then
      echo "Puppet is already installed"
    else
      wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
      dpkg -i puppet5-release-$(lsb_release -cs).deb
      apt-get -qq update
      apt-get install -y puppet-agent
    fi
  SHELL

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      # nodeconfig.vm.network :private_network, ip: node[:ip]
      if (node[:portfrom]) then
        nodeconfig.vm.network "forwarded_port", guest: node[:portfrom], host: node[:portto]
      end


      if (node[:modules]) then
        nodeconfig.vm.provision "install_modules", run:"always", type:"shell", path: "./puppet_modules.sh", args: node[:modules].join(" ")
      end
      # ruby är konstigt med block. För att detta låg utanför loopen exekverades det först.
      # Borde egengtligen ligga utanför, för att det ska köras för alla noder. Men då får jag inte det att exekveras i rätt ordning
      nodeconfig.vm.provision :puppet do |puppet|
        puppet.manifests_path = "./environments/test/manifests"
        puppet.manifest_file = "default.pp"
        puppet.module_path = "./environments/test/modules"
      end
    end
  end


end
