Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.hostname = "dk-ord-web01"
    config.vm.network "forwarded_port", guest: 80 , host:8084


    config.vm.provision "shell", path: "./bootstrap.sh"


    config.vm.provision "puppet" do |puppet|
        puppet.module_path = "./site"
        puppet.options = "--verbose --debug"
    end
end